### ISSUE TITLE
Sandy 

### ISSUE THREAD

**Issue by 56431614sandy** [MOXHARTZ/fivem-manager-bot-translations#11]
Hola babosos 
![IMG-20240204-WA0951](https://github.com/MOXHARTZ/fivem-manager-bot-translations/assets/158856723/2a2a8c7c-6d38-439e-b6e0-ed12f62e1c4a)
[map.md](https://github.com/MOXHARTZ/fivem-manager-bot-translations/files/14158605/map.md)

**Comment by MOXHARTZ** [comment]
hi, dickhead
